### ISSUE TITLE
Camera Level 2

### ISSUE THREAD

**Issue by Duskfen** [dominik-pm/CircleHead#12]
The field of view stops in level 2 too early.

**Comment by Duskfen** [comment]
the camera movement is specially programmed for level 1 i think

**Comment by dominik-pm** [comment]
I hob de 'camera bottom right' node bei level 2 und 3 nu ned noch unten rechts gschom :D

**Comment by dominik-pm** [comment]
easy fix, have fun

**Comment by Duskfen** [comment]
stimmt dankee
